#!/bin/bash
HERE="$(dirname "$(readlink -f "$0")")"
export CLUCKERS_BUNDLED_PROTON="$HERE/proton"
export LD_LIBRARY_PATH="$HERE/usr/lib:$HERE/usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH:-}"
exec "$HERE/usr/bin/cluckers" "$@"
